exception: Simplify the DBus::Exception::SetDBusError() for D-Bus invocations
The current API was not optimal as it made setting the D-Bus error domain
quite challenging from classes inheriting this exception class.

Instead make the D-Bus error domain a protected variable which the class
inheriting DBus::Exception can set directly.  Then the error domain
argument is also no longer needed in SetDBusError().

Signed-off-by: David Sommerseth <davids@openvpn.net>